# Generated by Django 5.2.1 on 2025-05-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('daraja', models.CharField(choices=[('boshlang‘ich', 'Boshlang‘ich'), ('o‘rta', 'O‘rta'), ('yuqori', 'Yuqori')], max_length=50)),
                ('davomiylik', models.CharField(max_length=50)),
                ('baho', models.FloatField()),
                ('reyting_izohi', models.CharField(max_length=100)),
                ('youtube_url', models.URLField()),
                ('youtube_img', models.URLField()),
                ('tomoshabinlar_soni', models.CharField(max_length=50)),
            ],
        ),
    ]
