# Generated by Django 5.2.1 on 2025-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='daraja',
            field=models.CharField(choices=[("boshlang'ich", "Boshlang'ich"), ("o'rta", "O'rta"), ('yuqori', 'Yuqori')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='reyting_izohi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
