# Generated by Django 5.2.1 on 2025-05-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_kurs_daraja_alter_kurs_reyting_izohi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField()),
                ('rasm', models.ImageField(upload_to='kitob_rasmlar/')),
                ('fayl', models.FileField(upload_to='kitob_fayllar/')),
            ],
        ),
    ]
