# Generated by Django 5.2.1 on 2025-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kitob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='nomi',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='fayl',
        ),
        migrations.AddField(
            model_name='kitob',
            name='fayl_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitob',
            name='rasm',
            field=models.URLField(),
        ),
    ]
