# Generated by Django 5.2.1 on 2025-05-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_nomi_kitob_nom_remove_kitob_fayl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='nom',
            new_name='nomi',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='fayl_url',
        ),
        migrations.AddField(
            model_name='kitob',
            name='fayl',
            field=models.FileField(default=2, upload_to='kitob_fayllar/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitob',
            name='rasm',
            field=models.ImageField(upload_to='kitob_rasmlar/'),
        ),
    ]
